---
title: "ch3"
author: "Dr Wayne Stewart"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,comment = "ws>")
```


# Vectors

## Types

Two types: Atomic and Lists

Vector has attributes
1. dimension
2. class

## Long vectors coercion

```{r}
v_dbl=c(3.1416, 2.3, -4.1, 1.2)
v_lgl = c(T,F,F,TRUE,T)

c(c(T,F),c(T,T,T,F,F))

```

```{r}
typeof(v_dbl)
```

```{r}
typeof(v_lgl)
```


 Coercion
 
```{r}
v_lgl
sum(v_lgl)
```
 
## Attributes

name value pairs
names and dim are preserved

```{r}
x = 1:10
attr(x, "name") = "value"
str(attributes(x))

attr(x,"y") = seq(1,100,by=2)
str(attributes(x))

x
```


## Class atrribute

```{r}
class(x) = "AdvancedR"
x
```


```{r}
factor(v_lgl)
factor(v_lgl, levels=c(TRUE,FALSE))

```


```{r}
vf1=factor(v_lgl)
vf2=factor(v_lgl, levels=c(TRUE,FALSE))
typeof(vf1)
typeof(vf2)
class(vf1)
class(vf2)

str(vf1)

summary(vf1)
```



## Lists

Create a list with list()

```{r}

lst1=list(a = 1:4, b = c(TRUE,TRUE,FALSE,TRUE,FALSE))

typeof(lst1)
class(lst1)
```



```{r}
lst1[[3]]  <- 1:5
lst1
```

```{r}
names(lst1) = c(names(lst1)[1:2], "new name")
lst1
```


## Data frames and matrices

You learn!!